# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-15 14:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Myfeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default=b'', max_length=255, null=True, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('description', models.TextField(blank=True, db_index=True, null=True)),
                ('tag_id', models.CharField(blank=True, db_index=True, default=b'', max_length=255, null=True)),
                ('main_link', models.URLField(db_index=True, default=b'', unique=True)),
                ('sub_link', models.URLField(db_index=True, default=b'', unique=True)),
                ('published', models.CharField(blank=True, db_index=True, default=b'', max_length=255, unique=True)),
                ('updated', models.CharField(blank=True, db_index=True, default=b'', max_length=255, null=True, unique=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, default=b'', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='appes.Category')),
            ],
        ),
    ]
