# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-15 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='myfeed',
            name='main_link',
            field=models.URLField(db_index=True, default=b''),
        ),
        migrations.AlterField(
            model_name='myfeed',
            name='published',
            field=models.CharField(blank=True, db_index=True, default=b'', max_length=255),
        ),
        migrations.AlterField(
            model_name='myfeed',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='myfeed',
            name='sub_link',
            field=models.URLField(db_index=True, default=b''),
        ),
        migrations.AlterField(
            model_name='myfeed',
            name='title',
            field=models.CharField(blank=True, default=b'', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='myfeed',
            name='updated',
            field=models.CharField(blank=True, db_index=True, default=b'', max_length=255, null=True),
        ),
    ]
