# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-15 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appes', '0002_auto_20171115_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myfeed',
            name='category',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
